### PR TITLE
Added print function in the code

### LINKED ISSUE #2: Issue_2
Create a print function for the script

### PR DESCRIPTION
**Pull request by kpuyam**
I added the feature to the code.
Closed #2

### CODE REVIEW

**Comment by Utkarsh5678** [comment]
i have made the necessary changes

**Comment by Tiger-rohan** [comment]
Please resolve the merge conflict

**Comment by kpuyam** [comment]
I resolved the merge conflict.

**Comment by Tiger-rohan** [comment]
Great work @kpuyam @Utkarsh5678  for solving the Merge Conflict

**Review by Tiger-rohan — APPROVED** [review]
Issue #2 Resolved

**Pull request merged**
